services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cursework-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/DB_SQLite:/app/backend/DB_SQLite
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cursework-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
